DROP TABLE IF EXISTS documents;
CREATE TABLE documents (
  id uuid CONSTRAINT documents_pkey PRIMARY KEY,
  type varchar(255),
  space varchar(255),
  status varchar(255),
  title varchar(255),
  "documentKind" varchar(255),
  "registrationDate" timestamp,
  "executionDate" timestamp,
  correspondent varchar(255),
  "correspondentTitle" varchar(255),
  "externalSigner" varchar(255),
  "externalExecutor" varchar(255),
  "externalNumber" varchar(255),
  "externalDate" timestamp,
  "documentNumber" varchar(255),
  "pagesQuantity" integer,
  "itemQuantity" integer,
  "appQuantity" integer,
  "comment" text,
  addressee varchar(255)[],
  "addresseeTitle" varchar(255)[],
  author varchar(255),
  signer varchar(255),
  "signerTitle" varchar(255),
  executors varchar(255)[],
  "executorsTitle" varchar(255)[],
  archivecase varchar(255)
);